apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: kube-system
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tailscale
          image: tailscale/tailscale:stable
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: true
          env:
            - name: TS_HOSTNAME
              value: "ts-subnet-router"
            - name: TS_LOGIN_SERVER
              value: "https://jump.yornik.nl"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_ROUTES
              value:  "10.69.0.0/16,10.96.0.0/16" # Replace with your cluster's Pod and Service CIDRs
          volumeMounts:
            - name: ts-state
              mountPath: /var/lib/tailscale
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: ts-state
          emptyDir: {}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

