---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: kube-system
