apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pixelfed-postgresql
  namespace: social
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.6.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      existingSecret: pixelfed-postgres-auth
    primary:
      persistence:
        enabled: true
        existingClaim: pixelfed-postgres-pvc
