apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixelfed-postgres-pvc
  namespace: social
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: truenas-iscsi
