apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-postgres-auth
  namespace: social
stringData:
  username: ENC[AES256_GCM,data:iKBGy1KFp1o=,iv:CODJBfKGciFf/JDj53J84y0DVAG/vtPV41p4wGOKeFg=,tag:sjtNZVIQ2wmNKjtB4HIEfg==,type:str]
  password: ENC[AES256_GCM,data:yQEm0FAMW0cQ4hOcPGsU5v2/uE4DK0UKhRhdFO0NWoM=,iv:wx22a3Ci5OErnHmtJI5O0ZK8gIV3PE90FrB9JBMlm4A=,tag:Xu6KX1pJTqxoi3oo0TFK5g==,type:str]
  database: ENC[AES256_GCM,data:ChO5xPUHQIk=,iv:8iEwR4v9CRkkPv0xNhoprmT+QWrHVyCvUJEuiqtivs4=,tag:ApPeSFDwxI7/V5KbuO7EZQ==,type:str]
  postgres-password: ENC[AES256_GCM,data:cvrSUudKJuXaOUuQR8gw1juHBJI3q+NJ56TYVQphfEY=,iv:8zY1T19z5GbJwGNRdqGwsidhKcFCsLetqhgfgEDr5gY=,tag:vTlckk8Ydv06b7dbiy6DnA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa1VrU0hHQVdDSFNYeXpZ
        Z1VmazIxUGFDczFTTURqUk1veWNFcXhIQmpFCkhaME5xVzJBcy9neUZDZ1NFbWl0
        bmp1QWJST2w5anFoNDhIT2V6WWlQWTgKLS0tIHZTaVUydGx4V3QxcUh6M3ptWVo1
        cnhlaHpySmVxUnJ1TkRhdERGRGE3VmMKutOCCyzyCrNeT3yNKjO17Fkpm/KMlwdb
        bPzli4piLuhDsB1WDt3sgmPzpePG28dP0CjnNzFr0Qu/Ol3+REOFuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-18T18:53:59Z"
  mac: ENC[AES256_GCM,data:rgJepQsRY3jnN9Yve8KlMKyL6MnIay51E1i6Xet80UR7pgrroqVoUA/uIuN0cJa+HMTtiSwN+aynBNpjp+x10O5Gl7oKougraE7rm7Fe3LwLvPHmynP2XuEvLr/dO54TmKCg6QG7bIKDRHclz18B0IvpbrO7REpeaTTRlQiW8JA=,iv:iTEiMYcvj7RIbfCN75hw82YGOfKkbDR1eRf+qmqXBgw=,tag:7m1TYgq50LqGYErsryITFg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
