apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-postgres-auth
  namespace: social
stringData:
  username: ENC[AES256_GCM,data:iKBGy1KFp1o=,iv:CODJBfKGciFf/JDj53J84y0DVAG/vtPV41p4wGOKeFg=,tag:sjtNZVIQ2wmNKjtB4HIEfg==,type:str]
  password: ENC[AES256_GCM,data:yQEm0FAMW0cQ4hOcPGsU5v2/uE4DK0UKhRhdFO0NWoM=,iv:wx22a3Ci5OErnHmtJI5O0ZK8gIV3PE90FrB9JBMlm4A=,tag:Xu6KX1pJTqxoi3oo0TFK5g==,type:str]
  database: ENC[AES256_GCM,data:ChO5xPUHQIk=,iv:8iEwR4v9CRkkPv0xNhoprmT+QWrHVyCvUJEuiqtivs4=,tag:ApPeSFDwxI7/V5KbuO7EZQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa1VrU0hHQVdDSFNYeXpZ
        Z1VmazIxUGFDczFTTURqUk1veWNFcXhIQmpFCkhaME5xVzJBcy9neUZDZ1NFbWl0
        bmp1QWJST2w5anFoNDhIT2V6WWlQWTgKLS0tIHZTaVUydGx4V3QxcUh6M3ptWVo1
        cnhlaHpySmVxUnJ1TkRhdERGRGE3VmMKutOCCyzyCrNeT3yNKjO17Fkpm/KMlwdb
        bPzli4piLuhDsB1WDt3sgmPzpePG28dP0CjnNzFr0Qu/Ol3+REOFuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T20:58:27Z"
  mac: ENC[AES256_GCM,data:URrLOwQL/KNb9FhAaYUHD8LpqmrYBDT3kzG/+aFhTZj/TJWEzoUu0b+fyMsYeyr5PoFw48wM7w0nmiYNi+TO5+QJzdyMCe+wnwvxABQaaM0f9hRI9cOUFJR8+vJlrnjgJAqXIFJW6+wMD8L4NvdK1cBRaO0Q7jYNjqOf0dX71Xs=,iv:Cvl9TPTbvxzRTPNwRQKAX7tcBkXYl0zegoJeQuKcv+g=,tag:cDGd95hrsj6BzL7JHOxESg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
