# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:++vSQvxdA3rz3WBt1PdlNf1/C0o8Njkb4KLBQo1ABMzxpMa6,iv:8kY3OyPeYEvwGkOIPlkml2dCbHUqb/ga0qDkOANQw7k=,tag:HSESf1zZQAAes7YttcZ3gA==,type:str]
  credentials.json: ENC[AES256_GCM,data:TJIYxBT5kVpga+2/2ObEz6YdT8foRm2NpEuFC5bBnIFzdBCRUi2bNVWetAddw1OsdZBTvbAF600KyF623jELmiboP4cRFMD+tRv+06t6aJeFVGalR6PA1dbsfXsABZJyG10q4Duw2wcdNHIEjhqSd+c0G6dXzBcacpE3URYF5yKJvQJDIQn7qhir6X56Ak6gCVmoK/sAT+Msw12POaalT/J1knsplVr/Z/9LWNaF9g==,iv:N/7VrpjtH2Wf4sxWovzFYzuMzTSkJLdHjWuhz92O4Uo=,tag:W2dtenr+Yeiutcad+9ITaA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWXozS0xvUmlROHdpMFpw
        VFBOTVZ0TDdoOWg0dWlrSW11RUdKczA4VFZzCmtkWjJtODEzK045Z1lHb0ovN2dB
        M1lsWCtQWWhOVWJXY2RJdkJzRDVQUTgKLS0tIEJjQlV2RmRBcDBKelkrK0k0YlFO
        bVpid3ZsMklIbk9HVE5UYThyd3ZGRDAKeCpzkDxGNSj3poWlzMGWmISemSV/XAoa
        L6RT+mxgf1/zHYL5obM3IO5CTT9qAluyCjkWiWjfsh5rD6W1cjOoJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T22:51:26Z"
  mac: ENC[AES256_GCM,data:0unV4KniHPrnC56gTXhd5SslnWlwfMmdJZJ9HZ0q2Hng4+i4Q2zbeytVoq/l7daIisqsvPcVM2ji2CV4a/bNQ32Cq0pyARQXCe0kZHqSuvuDFO4oHtb5ipPJSkbm3OZBOouUdb6i+k6PkY0ir9yWIThlu7ZgmRDE5XEG3w67lXI=,iv:AYjIvApHHEqJHUzrMAUTt53qLdUfZ8fOr1M6aY2sVRU=,tag:iliXswNDMYVza9I0DBVN7g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
