# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:W+G6izUXdXnbYSc+aq6ovJ5dDbLjgEMGegoHvzhCLHdqeuVp,iv:Mej3hepmuU0kXlelSqXLBVS7KTZPztSMT5/adOyKJn4=,tag:KHsMGfqAmIAoxSPI98I55w==,type:str]
  credentials.json: ENC[AES256_GCM,data:GT5vGbT6r68BlWYNmlLN76LdmubroYrUibXlUV5zLNUJy61KLl6mCtThaGfhzFxJY0W38hb7bV0HhLX09iWMVbIPBSToK5SBRmcj5jUChZ810Q4h1dTm+Jut8xoBq75lw0JdhzqxqTHqNZSHOLj1NjkIK1jI1zR3nx/rl1N9ZhNzCrekUaM2DWT6Y5ff/dj3zMlDUxUQ2/c1a7OLs/5vCn1sAWpnozp2/FxKmuGXiA==,iv:6yi4yF4iBh+XDK4Ocmr3m/gr+V7KpWEBtwAicyKt4TM=,tag:8K4CxYxeQ+oxO5FDrUJxiw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ3pOZUErVDc0alhvQVd0
        OTJQZzNhUE0wQ1lDT1NiVDFUMElkWDlzVWxRCkVaTFpiWWl3alV0VjF2b3NNYW9V
        eTJhOHNidlRmdk4xWC9mUXpkTVJ4Q1kKLS0tIGtKY3RPWUtPWjRoSzBIZjI5eUVE
        US91R1lNaGtUeTI1dHpaSUdYSjNldE0KvQQ08fqHOzpXM8zx8O16ycDgn78pPila
        XMUDnLNSUn50Sah4tEQ9Q6LJB5tbP8bqA71WGBCLa32wmpynhYqyxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-19T00:12:12Z"
  mac: ENC[AES256_GCM,data:V9/D7INWFKUFNfuatT1G8PS/lYtbVEsFcauC/xX3UhvfRPaMUIqOfsVxGo18Isv6jTXF9q6pMTylNDERdzt0a9oXCaBxLgHIwIALdT0ba2Fx9r94MVs3ieA0SzwLSIb2j/kVawdpTYFSDueaOA4AoHpDFz4nyMXwQHSZGcKGtTA=,iv:mWwSMy7wFSQ8GHSlO2mG1WgkCE1U/JyM1raeKDcXYMU=,tag:jPVpaA1/kX2bMSXIBV08gg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
