---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: external-dns
    provider: pdns
    extraArgs:
      - --pdns-server=https://dnsapi.yornik.nl
      - --pdns-api-key=$(PDNS_API_KEY)
      - --txt-owner-id=default
      - --domain-filter=yornik.eu
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external
    env:
      - name: PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: api-key
    policy: sync
    sources:
      - crd
      - ingress
    txtPrefix: k8s.
    domainFilters:
      - yornik.eu
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret

