# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:D45tlbLmppfREmMuCfbvIngZCrZX86sV6Qdg0KhzzRfsXHwtHn/4Ug==,iv:E6ilzg3p4uap8MBJ09xR5MXs6Q/Y39i2/qyrC0MMf5g=,tag:d8uwqE8PhWIx/ehnL6w2pw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b1pwTjJoZFY0K1lMRWR3
        YTk3d2xKSjJXVnVKZWQ3Y0RuT3Y5dWFPMDJBCmpHbEdydXNFaEpwNUxoczVkZ0Ry
        VHJhNk1yZDVqUEVzRDBnOTNkQjh0dDAKLS0tIFh2dyt5WCt0TUtKV0xFQzY2RWlN
        S1Z4eXp6TGlBK0g2U3VldkpWMXh6d2cKzE8A1f88kUL9mFPNq1oNvWZWzq3keKZn
        NZQNII5ZqFSB5PtI9wMk1XXe4ZTl6huIds5pzpSpRmrE5Z6NTwE4Uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T22:30:19Z"
  mac: ENC[AES256_GCM,data:bvzig+7UgE5mWaGZwk+/iFuBlwSXSMVYKxrNqf5w1t2CLOTfaphn8xlafZhfkRrv45E3RzDK2eFSlEhjurZWpBZOGxOZnW2STUJdH9M+GGedgCQwe/BDGZtF5m7BZetprN6dDY7gIebKdtmBjA08clwNn4ThwJUZu9RYTQeAs+A=,iv:COCUpDhIPNtY1PnAv61WI2DnrofecFmhuTiawkNRLm0=,tag:fAK/dlw4EcgfXOMWMj+w4w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
