---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-pdns
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-pdns
      version: 2.5.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-pdns
        namespace: cert-manager
  values:
    groupName: acme.yornik.eu
