apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixelfed-media-pvc
  namespace: social
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-iscsi
