apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: kube-system
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:4Cqz1Lnscp21W09uM3dWwhX6qhsx6Pz3AC5K8QFWX5eCcMTWz/IW9/GXDRUNqQ8/,iv:090lOLJqFSWcC659VANHUfB6cs4X12YqbYMsUU0Wyqs=,tag:VxPdSZRFHBF12wRqM0Updw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV01ETnZXSW1ZZmtaM1hT
        eUt1elltTllINHhjYkxsZkJjelhCT1Q3N2k4CmdqcjRZVWJoN3BNdXFlbE45MkVv
        eHF5cjQ5REh1YVA3cGdQNW5oTW5CTW8KLS0tIDMzR2syaUtpWDJacGh5M3BPVGVi
        cEVUOUpMekd3ZmVMNnRFd0xBZFRnYWMKP/szDd3xUomKnr7GauAEEip6fGUQa+jp
        WiktNAcwhFGn06LSfVJrHUNLHh1w9HyAwyVfMZvAM5UP/yvtqRghkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-24T21:18:19Z"
  mac: ENC[AES256_GCM,data:BuKtIsM5y7xJ84JBpH68o2BhpgTI+OufxlXaygvTKBm64x4RtRfvSLvsrTlt7qaAG7Nj4tcBE8nnfdfRLh7YheEv+rxTII05gH+C0uMOM5x6cRZTQy4bsmLlDEgwCNQKC7TYJb1OYmzr9rtryHrbJE2K6OR8q9Yzd4kIv2sbNQk=,iv:+eiIWM4lVZxjRoTAlBCGHBjcKMUuFnsQXtYk6tuTFNA=,tag:pyS5Ims3ZPbjpxEUWv+9Dw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
