# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:VOvINxF+d6dE6WQeuqgVvUu4R1Rc9s2TyL1fnepJx4ggyP++nATjlA==,iv:sl9qgBFerWIa9ueTdrkOyqx9jlXBlzsnIxWhBRKby0I=,tag:LbWFg7CKAeLz/2nTj0c2Cg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb2JwWkF0eFlxdzgvVmVG
        TTQ4bDVjTzNON0lPL3lrWU1OZnVodGhOR1djCitkSUJMYWhreUh0ZXdxTGhtb2hI
        MEFUVUxpMGZMTGtVQURDQlZuUjZBWjQKLS0tIDdFbmNFTWJ4aXFsM2pOdERHZitX
        VS9BNmhUMUQ4c0ErUSsrOWxzbWI3T3MKyzvQRcOQz/CNTTtu44u3ed10pKiI+qoA
        2nAsowxvewcmATWW+Nv2/xLy/YoM2VgKYvy12Oo7HlHW3Jzv7lLVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-19T00:12:12Z"
  mac: ENC[AES256_GCM,data:G5m/xaTi5Bpq6pFFThSichjGtuuEOrE4/QJMVbTmnbH8s5bWnDAcJAxox+KVPlzkY4wdtYfQfJctVmlUF438Bz2mJ5GQarQ4j6uuj6MaxqhXbRdrQSZf/TnrVl4NYHIzo/qh5iAI45zvQxYvv+QWRJa/xVap4ePIBBiMKT1sCvA=,iv:Fvb2Yh34yqwjzV9uSl9luxaT6mDNSk3stxrsGX0QChM=,tag:TDLLq7FaQfmuKpa+updZMw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
