# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: powerdns-api-key
stringData:
  api-key: ENC[AES256_GCM,data:rDJH+JtZv1EfAxXwpD3lxOUgbDRqoPC8yFA19OHwLls=,iv:0BxBrdAhboFEDF2Ivi2BY6O+Gimg772kDAoagUllpME=,tag:SWKJyb5HFN/CVGqRQUW2lQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb2JwWkF0eFlxdzgvVmVG
        TTQ4bDVjTzNON0lPL3lrWU1OZnVodGhOR1djCitkSUJMYWhreUh0ZXdxTGhtb2hI
        MEFUVUxpMGZMTGtVQURDQlZuUjZBWjQKLS0tIDdFbmNFTWJ4aXFsM2pOdERHZitX
        VS9BNmhUMUQ4c0ErUSsrOWxzbWI3T3MKyzvQRcOQz/CNTTtu44u3ed10pKiI+qoA
        2nAsowxvewcmATWW+Nv2/xLy/YoM2VgKYvy12Oo7HlHW3Jzv7lLVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T00:11:57Z"
  mac: ENC[AES256_GCM,data:s29DQQKYSeHKMnDiE9O0rKeZes/f3ahhq0wVH6wbl15uuwizitP1c6qltIS31NcLDt+Rn8sREA7xDsW6pOj72u2GUTF7Pv0ev0i0tZ8eQpvSs8QONo0YHcv8gw9EKhpyw2WrtwFY50LpDpEfsXQq/mgHHLc7CW5WMhLeQJQ2Nl4=,iv:E37qdFdtopv6dGlPUwkNzqk8Ab/5GdaIpFDvDdz2db4=,tag:gNyb2Sn0cjOOnpTqV7saqg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
