# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kBbgOCNcT2dNnk4GzdFhIeZv6dpcQMJJQLDtUmFLL8BOjcsyWchveg==,iv:T+HEEbvBLPumSyfulaRv4/A77E3WWHH4EUIuEtj+ohE=,tag:As7Y7+5g5ytt5oXaXY9CiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRzd6cXpRY084SlhYWDNu
        S2h5dXVwcURrQmo5YkxMUFRSS2JlbnQ4YVV3Ck9JdlJHR2JoMVhHVlNWRStUa081
        Um90Z2s4ODdzVHplWkZnNUZqcHRSUUUKLS0tIHpKQ1hrRmpRTTVQTkExc2tId0s0
        bWtKN1k1QlQycnVya3Y2Qjd2M0hSK1UKGDQx7zhAfiNYYHnda946gAQFjCGzYZdp
        3XoNbA0pzPzpfWnZHVPZeBq9XJHobEtj4fMOC2Bj6UX24j5Zc9K1SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T22:51:26Z"
  mac: ENC[AES256_GCM,data:D3wcNcytOjMo/ToNCak+uLvm6VX+3pz6mR/FidzV6VwmiW1qQI/Rvv/kCCM/aknwcz78nTTJMEyxMCH9IQFYYMDsnVo4Wup7G9Gvb1T/n9M+rNRCmgvL7AzGEU4jJAwEgpVsd44k5+AWju3/aQSTgxRYdttiNMU4Fv7U9dovqvc=,iv:L+beX/oyfZE+s/11JfsdxxoMhtk1Ex3csbGxIYynDLg=,tag:zh+X5JrESOMsuSAHClLayw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
