apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscaled
  namespace: network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscaled
  namespace: network
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "create", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscaled
  namespace: network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscaled
subjects:
  - kind: ServiceAccount
    name: tailscaled
    namespace: network
