apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: flux-system
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:4Cqz1Lnscp21W09uM3dWwhX6qhsx6Pz3AC5K8QFWX5eCcMTWz/IW9/GXDRUNqQ8/,iv:090lOLJqFSWcC659VANHUfB6cs4X12YqbYMsUU0Wyqs=,tag:VxPdSZRFHBF12wRqM0Updw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q757hdrk9l7ukrxy7qgjrfu09226kyts59tqh83t5y7q0f0cfy3sv430e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV01ETnZXSW1ZZmtaM1hT
        eUt1elltTllINHhjYkxsZkJjelhCT1Q3N2k4CmdqcjRZVWJoN3BNdXFlbE45MkVv
        eHF5cjQ5REh1YVA3cGdQNW5oTW5CTW8KLS0tIDMzR2syaUtpWDJacGh5M3BPVGVi
        cEVUOUpMekd3ZmVMNnRFd0xBZFRnYWMKP/szDd3xUomKnr7GauAEEip6fGUQa+jp
        WiktNAcwhFGn06LSfVJrHUNLHh1w9HyAwyVfMZvAM5UP/yvtqRghkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-18T19:37:19Z"
  mac: ENC[AES256_GCM,data:5QD5BVeHn0mLUi+Y2CMS6ClUxLIKseMvdIECh2r4TgeFqE92pU1kqNTuCKmTvr9KXDcZM9vzseq2vaHScJB5TXY2+0Byr/4BsTnb5IybqKbdU6V8lusp+mBd3ZTqrSpxQIjWJx8mUW3OHRmDu94gRz43WICXuU6/Nh7g356s/Uo=,iv:hqP6viszuXhBnuG6JGuOprD//MZ4uljHzOFmJr4kYno=,tag:XQyHPOdwGEknKJfluvv92g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
