apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: infra
spec:
  releaseName: redis
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "20.11.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: false
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: truenas-iscsi
        size: 1Gi
