apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: infra
spec:
  releaseName: redis
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: flux-system
  values:
    auth:
      enabled: false
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: truenas-iscsi
        size: 1Gi
