---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
  - ../../flux/components/common
resources:
  - ./flux-operator/ks.yaml
  - ./capacitor/capacitor-source.yaml      # the OCIRepository definition
  - ./capacitor/capacitor-base.yaml 
  - ./capacitor/ks.yaml                    # wrapper Kustomization with Tailscale overlay
