---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: tailscale
          image: tailscale/tailscale:stable
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
          volumeMounts:
            - mountPath: /var/lib/tailscale
              name: ts-state
            - mountPath: /dev/net/tun
              name: ts-tun
      volumes:
        - name: ts-state
          emptyDir: {}
        - name: ts-tun
          hostPath:
            path: /dev/net/tun
