apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 10m0s
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-repo
        namespace: democratic-csi
  valuesFrom:
    - kind: Secret
      name: truenas-api-secret
      valuesKey: apiKey
      targetPath: driver.config.httpConnection.apiKey
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: truenas-nfs
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4

    driver:
      config:
        driver: freenas-api-nfs
        instance_id: "truenas-nfs-instance"
        httpConnection:
          protocol: https
          host: nas.yornik.nl
          port: 443
          allowInsecure: false
        zfs:
          datasetParentName: 'Big_Pool/k8s'
          detachedSnapshotsDatasetParentName: 'Big_Pool/k8s_snapshots'
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.1.42
          shareMaprootUser: root
          shareMaprootGroup: root

    controller:
      driver:
        image:
          tag: next

    node:
      hostPID: true
      driver:
        image:
          tag: next
        securityContext:
          privileged: true
        volumeMounts:
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: kubelet-pods
            mountPath: /var/lib/kubelet/pods
          - name: kubelet-plugins
            mountPath: /var/lib/kubelet/plugins

      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: kubelet-plugins
          hostPath:
            path: /var/lib/kubelet/plugins
