apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 10m0s
  releaseName: democratic-csi-iscsi
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-repo
        namespace: democratic-csi
  valuesFrom:
    - kind: Secret
      name: truenas-api-secret
      valuesKey: apiKey
      targetPath: driver.config.httpConnection.apiKey
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
      - name: truenas-iscsi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: xfs
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: "trueinas-iscsi-instance"
        httpConnection:
          protocol: https
          host: nas.yornik.nl
          port: 443
          allowInsecure: false
        zfs:
          datasetParentName: 'Big_Pool/k8s/iscsi'
          detachedSnapshotsDatasetParentName: 'Big_Pool/k8s_snapshots/iscsi'
        iscsi:
          targetPortal: "192.168.1.42"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 6
              targetGroupAuthType: None
    node:
      hostPID: true
      driver:
        image:
          registry: ghcr.io/yornik
          repository: democratic-csi
          tag: test-fix
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    controller:
      driver:
        image:
          registry: ghcr.io/yornik
          repository: democratic-csi
          tag: test-fix
