csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs

driver:
  config:
    driver: freenas-api-nfs
    httpConnection:
      protocol: https
      host: nas.yornik.nl
      port: 443
      apiKey: not-valid
      allowInsecure: false
    zfs:
      datasetParentName: Big_pool/Share
      detachedSnapshotsDatasetParentName: Big_pool/Share
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: 192.168.1.42
      shareMaprootUser: root
      shareMaprootGroup: root

