apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.7.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
    prometheus:
      prometheusSpec:
        scrapeInterval: "15s"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: truenas-iscsi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 35Gi          
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: "6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: "http://loki-loki-distributed-gateway.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      snippets:
        pipelineStages:
          - cri: {}
    extraArgs:
      - -config.expand-env=true
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    serviceMonitor:
      enabled: true

