apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.7.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
    prometheus:
      defaultRules:
        create: true
        rules:
          kubernetesSystem: true
        disabled:
          - KubeProxyDown
      prometheusSpec:
        scrapeInterval: "30s"
