apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.7.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
      persistence:
        enabled: true
        type: sts
        storageClassName: "truenas-iscsi"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
    prometheus:
      prometheusSpec:
        scrapeInterval: "15s"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: truenas-iscsi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 35Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-distributed
      version: "0.80.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      common:
        replication_factor: 1
        ring:
          kvstore:
            store: memberlist
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: "2023-01-01"
            store: tsdb
            object_store: filesystem
            schema: v12
            index:
              prefix: tsdb_index_
              period: 24h
      storage_config:
        tsdb_shipper:
          active_index_directory: /var/loki/tsdb-index
          cache_location: /var/loki/tsdb-cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
      compactor:
        working_directory: /var/loki/compactor
        shared_store: filesystem
      limits_config:
        retention_period: 336h
    ingester:
      replicas: 2
      maxUnavailable: 1
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      persistence:
        enabled: true
        claims:
          - name: data
            size: 15Gi              
            storageClass: truenas-iscsi    
    distributor:
      replicas: 2
      maxUnavailable: 1
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    querier:
      replicas: 2
      maxUnavailable: 1
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
    queryFrontend:
      replicas: 1
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      persistence:
        enabled: false  # Disable per-pod PVC creation
      extraVolumes:
        - name: loki-share
          persistentVolumeClaim:
            claimName: loki-shared-nfs
      extraVolumeMounts:
        - name: loki-share
          mountPath: /var/loki
    compactor:
      compaction_interval: 5m
      replicas: 1
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
      persistence:
        enabled: false  # Disable per-pod PVC creation
      extraVolumes:
        - name: loki-share
          persistentVolumeClaim:
            claimName: loki-shared-nfs
      extraVolumeMounts:
        - name: loki-share
          mountPath: /var/loki
    indexGateway:
      persistence:
        enabled: false  # Disable per-pod PVC creation
      extraVolumes:
        - name: loki-share
          persistentVolumeClaim:
            claimName: loki-shared-nfs
      extraVolumeMounts:
        - name: loki-share
          mountPath: /var/loki
    ruler:
      persistence:
        enabled: false  # Disable per-pod PVC creation
      extraVolumes:
        - name: loki-share
          persistentVolumeClaim:
            claimName: loki-shared-nfs
      extraVolumeMounts:
        - name: loki-share
          mountPath: /var/loki
    serviceAccount:
      create: true          
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: "6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    auth_enabled: false
    ingester_client:
      remote_timeout: 30s
    config:
      clients:
        - url: "http://loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
      snippets:
        pipelineStages:
          - cri: {}
    extraArgs:
      - -config.expand-env=true
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    serviceMonitor:
      enabled: true

