apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-shared-nfs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: loki-shared-nfs-pv
